### ISSUE TITLE
Specify SF Instant runoff election

### ISSUE THREAD

**Issue by jldodds** [cjerdonek/formal-rcv#1]
This is the "mathematical" specification of the election, that may not be computable or deterministic, but that will clearly convey the same meaning as the document

**Comment by cjerdonek** [comment]
I have one more initial thought / suggestion on this issue after starting to review @robdockins's initial work on this here: 921bc8ca70b19aa548475ae7bf062c4cb47fdb2b.  (Also see my two comments on the commit itself.)

In terms of developing / deriving a specification from statute language, I think it would be very helpful if the definitions and specification statements / properties to be proved appear immediately after where they are mentioned in the statute itself.  So you would have the full statute language interleaved line by line with the statements to be proved.  This approach would also let one see which statements to be proved don't derive from the statute language itself.

For example, after a sentence like this--

> If a ranked-choice ballot gives equal rank to two or more candidates, the ballot shall be declared exhausted when such multiple rankings are reached.

you could include the corresponding property that this translates to in Coq.

Of course, if it makes sense to define introductory concepts before starting through the statute language itself, that could also still be done.

@robdockins Does that seem possible after having already worked on it for SF?

**Comment by robdockins** [comment]
@cjerdonek I like the style that you're proposing; but I'm not sure how well it will work in this case.

The problem is that Coq is from the ML style of languages, which means that there cannot really be any forward references.  In particular, definitions must precede their uses, so one is forced into a bottom-up order of giving definitions.  Natural language definitions are not always written in this style, so making them match up one-to-one like that will be difficult, unless we alter the order of the statue text.

The alternate style you propose (with a series of definitions preceding the statute text, which is then intercut with proved properties) is probably more achievable.

**Comment by cjerdonek** [comment]
@robdockins The alternate style sounds fine then.  I figured that might be a limitation.

To summarize, for a specification from a statute--
1. Start with the definitions in whatever order necessitated by Coq, etc.  For each definition, precede the definition with the relevant excerpts of the statute text (if there are any) as a Coq code comment.
2. Follow the definitions with the _full_ statute text in order.  As properties to be proved occur within the text, interleave the statute text with corresponding properties translated into Coq.
