### ISSUE TITLE
Ties in SF

### ISSUE THREAD

**Issue by jldodds** [cjerdonek/formal-rcv#8]
During elimination, are all candidates with the lowest number of votes eliminated simultaneously?

So if candidate A has 2 votes, B has 1, and C has 1, should both B and C be eliminated?

There is language about a tie for winners. Does a tie occur when the final two candidates are eliminated simultaneously? This seems like the only possibility; there can't be a tie otherwise when we are looking for a majority

**Comment by cjerdonek** [comment]
> During elimination, are all candidates with the lowest number of votes eliminated simultaneously?

@jldodds In general, no.  The only case where multiple candidates are eliminated simultaneously is with the so-called "batch elimination" rule.  This is described in Section [13.102(e)](https://github.com/cjerdonek/formal-rcv/blob/f313b7fc1550c96537906ef145744d161da08e97/statutes/san_francisco.txt#L52).  This is essentially an optimization in the sense that it doesn't change the outcome.  The outcome would be the same, so it is just "speeding up" the count by reducing the number of rounds.  (This is particularly useful when there are many fringe candidates with just a few votes each who can all get eliminated in the first round or so.)

As far as ties, ties need to be resolved when there is a tie for last place and the batch elimination hypothesis doesn't apply.  I will need to look up what SF does in this case, but it's not spelled out in the statute (it was an administrative decision).  I believe SF does something like draw straws among the candidates tied for last place.

**Comment by cjerdonek** [comment]
> So if candidate A has 2 votes, B has 1, and C has 1, should both B and C be eliminated?

Also, batch elimination wouldn't kick in in this scenario since 1 + 1 isn't strictly less than 2.  And if it were, then A would win by majority anyways, so there wouldn't be a need to eliminate.

**Comment by cjerdonek** [comment]
Sorry, one more note just to be clear since the Charter wording is a bit confusing.  Batch elimination doesn't require the bottom candidates to be tied for simultaneous elimination -- only that the sum of their votes are strictly less than the next candidate.  Also, it is always the _maximal_ such group that should be eliminated.

For example, if the vote totals are the following: 1, 2, 4, 8, 9; then you would eliminate the bottom three candidates since 1 + 2 + 4 < 8.  (1 + 2 is also less than 4, but that's not the "maximal" such group.)  Another way of thinking of this style of elimination is as "inevitable" elimination, since if the candidates were eliminated sequentially they would all be eliminated no matter how the votes transferred.

**Comment by jldodds** [comment]
That makes sense. So in this document a tie is an elimination tie, not a winner tie. The implementation should be parameterized by a function that decides a tie between some number of candidates
